// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type LandingDocumentDataSlicesSlice = ProductsComparisonsSlice | LogoSlice;

/**
 * Content for Landing documents
 */
interface LandingDocumentData {
	/**
	 * Slice Zone field in *Landing*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<LandingDocumentDataSlicesSlice>
	/**
	 * Meta Description field in *Landing*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: landing.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Landing*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: landing.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *Landing*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: landing.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * Landing document from Prismic
 *
 * - **API ID**: `landing`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<LandingDocumentData>,
	'landing',
	Lang
>;

export type AllDocumentTypes = LandingDocument;

/**
 * Primary content in *Logo → Primary*
 */
export interface LogoSliceDefaultPrimary {
	/**
	 * title field in *Logo → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * img field in *Logo → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo.primary.img
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	img: prismic.ImageField<never>;

	/**
	 * position field in *Logo → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo.primary.position
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	position: prismic.SelectField<'left' | 'right'>;

	/**
	 * size field in *Logo → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo.primary.size
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	size: prismic.SelectField<'lg' | 'sm'>;

	/**
	 * description field in *Logo → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;

	/**
	 * detailsId field in *Logo → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logo.primary.detailsid
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	detailsid: prismic.KeyTextField;
}

/**
 * Default variation for Logo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<LogoSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Logo*
 */
type LogoSliceVariation = LogoSliceDefault;

/**
 * Logo Shared Slice
 *
 * - **API ID**: `logo`
 * - **Description**: Logo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoSlice = prismic.SharedSlice<'logo', LogoSliceVariation>;

/**
 * Primary content in *ProductsComparisons → Primary*
 */
export interface ProductsComparisonsSliceDefaultPrimary {
	/**
	 * productId field in *ProductsComparisons → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: products_comparisons.primary.productId
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	productId: prismic.KeyTextField;

	/**
	 * designs field in *ProductsComparisons → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: products_comparisons.primary.designs
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	designs: prismic.NumberField;

	/**
	 * revisions field in *ProductsComparisons → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: products_comparisons.primary.revisions
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	revisions: prismic.NumberField;

	/**
	 * highRes field in *ProductsComparisons → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: products_comparisons.primary.highres
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	highres: prismic.BooleanField;

	/**
	 * 3dmockup field in *ProductsComparisons → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: products_comparisons.primary.3dMockup
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	'3dMockup': prismic.BooleanField;

	/**
	 * sourceData field in *ProductsComparisons → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: products_comparisons.primary.sourcedata
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	sourcedata: prismic.BooleanField;

	/**
	 * fbPic field in *ProductsComparisons → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: products_comparisons.primary.fbPic
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	fbPic: prismic.BooleanField;

	/**
	 * deliveryTime field in *ProductsComparisons → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: products_comparisons.primary.deliveryTime
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	deliveryTime: prismic.NumberField;
}

/**
 * Default variation for ProductsComparisons Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductsComparisonsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ProductsComparisonsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *ProductsComparisons*
 */
type ProductsComparisonsSliceVariation = ProductsComparisonsSliceDefault;

/**
 * ProductsComparisons Shared Slice
 *
 * - **API ID**: `products_comparisons`
 * - **Description**: ProductsComparisons
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductsComparisonsSlice = prismic.SharedSlice<
	'products_comparisons',
	ProductsComparisonsSliceVariation
>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig,
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			LandingDocument,
			LandingDocumentData,
			LandingDocumentDataSlicesSlice,
			AllDocumentTypes,
			LogoSlice,
			LogoSliceDefaultPrimary,
			LogoSliceVariation,
			LogoSliceDefault,
			ProductsComparisonsSlice,
			ProductsComparisonsSliceDefaultPrimary,
			ProductsComparisonsSliceVariation,
			ProductsComparisonsSliceDefault,
		};
	}
}
