// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from 'vue';
import { defineSliceZoneComponents } from '@prismicio/vue';

export const components = defineSliceZoneComponents({
	logo: defineAsyncComponent(() => import('./Logo/index.vue')),
	products_comparisons: defineAsyncComponent(() => import('./ProductsComparisons/index.vue')),
});
